### ISSUE TITLE
Error about "interpreter.set_tensor(input_details[0]['index'], input_data)"

### ISSUE THREAD

**Issue by JSnobody** [kmfrick/TFLite_DeepLabv3_Inference#1]
Hello! I get a error when I run it on ARM platform.

Traceback (most recent call last):
  File "inference.py", line 37, in <module>
    interpreter.set_tensor(input_details[0]['index'], input_data)

ValueError: Cannot set tensor: Got value of type STRING but expected type FLOAT32 for input 183, name: sub_7 

How to solve it?
Thanks a lot!

**Comment by kmfrick** [comment]
Try wrapping the second argument into `tf.dtypes.cast()`, like  `interpreter.set_tensor(input_details[0]['index'], tf.dtypes.cast(input_data, tf.float32))`

**Comment by JSnobody** [comment]
Hello, Sir!
Thanks for replying!
Now I am using tensorflow=1.10 version and I use tf.cast instead of tf.dtypes.cast.
like
```
input_data = tf.cast(input_data, dtype=tf.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
```
But the error is the same as before.
Can you help me?
Thanks very much!

**Comment by kmfrick** [comment]
`requirements.txt` specifies that `tensorflow>=2.2.0rc1` is required. Can you try using a supported version of TF and see if it works?

**Comment by JSnobody** [comment]
Hello, Sir!
I am sorry that I can not use tensorflow2.2.0. I tried to install tensorflow>=2.2.0rc1 on my ARM platform but failed!

I was really puzzled by something!
1. At first, I did not use tf.cast or tf.dtype.cast,  I printed `input_data`before `set_tensor` and it showed `Tensor("Reshape:0", shape=(1, 257, 257, 3), dtype=float32)`. 
I think the type of the input_data is already float32, and it seems right!
2. The second, I tried tf.cast, but it seemed that tf.cast did not work at all!
Is there a version requirement between TensorFlow and TensorFlow Lite?
3. The third, I considered using np.reshape instead of tf.reshape, but failed also.
How to modify correctly?

Thanks very much!

**Comment by kmfrick** [comment]
Which platform are you working on? 

Installing `tensorflow` will install the `tensorflow.lite` module, too, so both will be on the same version.

At some point you need to convert the input image to a `tf.Tensor`. I used `tf.reshape`, but you can also use `np.reshape` and then call `tf.Tensor`'s constructor, or use `tf.identity`.

**Comment by JSnobody** [comment]
Platform: RK3399 based on ARM V8, like Raspberry Pi. 
I install tflite_runtime, and install tensorflow1.10.
[https://tensorflow.google.cn/lite/guide/python?hl=zh-tw&authuser=0](url)
And I add
`import tflite_runtime.interpreter as tflite`
and change to
`interpreter = tflite.Interpreter(model_path=args.model_file)`

Maybe that is a question!

**Comment by JSnobody** [comment]
Hi，I tried to use np.reshape and np.argmax. 
But the results I got were black.

**Comment by kmfrick** [comment]
You mean you got an entirely black image as a result?
That is usually caused by one of two things:
1) You are argmaxing over the wrong axis. Can you post a minimum working example of your code?
2) You are running inference on images that look absolutely nothing like the training set. Try using some of the images from the [ADE20K val split](http://groups.csail.mit.edu/vision/datasets/ADE20K/dataset_browser/).

**Comment by JSnobody** [comment]
Yes! The results were black images!
I just modified two points:
1. from 
    `input_data = tf.reshape(input_data, input_shape)`
    to 
     `input_data = np.reshape(input_data, input_shape)
      input_data = input_data.astype(np.float32)`
2. from
    `output_classes = np.uint8(tf.argmax(output_data, axis=3)[0])`
    to
    `output_classes = np.uint8(np.argmax(output_data,axis=3)[0])`
For example:
    test image:
![1](https://user-images.githubusercontent.com/30650825/81760981-4b584680-94fb-11ea-9ff0-40fe7f6002fb.jpg)
    result:
![result](https://user-images.githubusercontent.com/30650825/81761001-57dc9f00-94fb-11ea-8878-8788c2adc62f.jpg)

**Comment by JSnobody** [comment]
test image:
![2](https://user-images.githubusercontent.com/30650825/81761063-8490b680-94fb-11ea-93d8-bf3cd8e5c388.jpg)
result:
![result](https://user-images.githubusercontent.com/30650825/81761073-8c505b00-94fb-11ea-8074-83193686c78d.jpg)

**Comment by JSnobody** [comment]
I do not know whether `output_classes = np.uint8(np.argmax(output_data,axis=3)[0])` is correct or not?

Thanks very much!

**Comment by kmfrick** [comment]
The output you are getting is correct, as well as the command you are using. From the colormap, I assume you are using DeepLab trained on the PASCAL VOC dataset. Your first image is well segmented (you can add a `cv2.resize` followed by a `cv2.addWeighted` to overlay the segmentation over the original image), as for the second...well, you just discovered one of the pitfalls of machine learning: your dataset has to look at least vaguely like the one your netwoks were trained on.

**Comment by JSnobody** [comment]
Oh, I see. That's why. 
However，does it show that the deeplabv3 network has not good generalization performance？
That is very interesting，and then I will test on the PASCAL VOC dataset！

THANK YOU!

**Comment by JSnobody** [comment]
Hello, I tested some images on the PASCAL VOC dataset.
But the result was not ideal!

For example:

![2008_000035](https://user-images.githubusercontent.com/30650825/81783207-98551080-952d-11ea-943b-772ddbe34694.jpg)  
![result](https://user-images.githubusercontent.com/30650825/81783223-9c812e00-952d-11ea-8ed6-90e6fbc04f43.jpg)

![2008_000013](https://user-images.githubusercontent.com/30650825/81783274-adca3a80-952d-11ea-8aa1-e3f61adeea06.jpg)
![result1](https://user-images.githubusercontent.com/30650825/81783285-b15dc180-952d-11ea-837f-88701ed0dec7.jpg)

![2008_000022](https://user-images.githubusercontent.com/30650825/81783380-d4887100-952d-11ea-98a9-94210cb0aa80.jpg)
![result](https://user-images.githubusercontent.com/30650825/81783404-db16e880-952d-11ea-80aa-8368d796a698.jpg)

**Comment by kmfrick** [comment]
Since DeepLab is the current state of the art, I guess this is a good time for you to brush up on your ML research skills and devise a model with better results then ;)

**Comment by JSnobody** [comment]
YES，you are right！
Make great efforts together!
Thanks for your help！
Grazie！Grazie！
